🧪TEST: revert the changes for deployment

diff --git a/packages/summary-codecoverage/action.yml b/packages/summary-codecoverage/action.yml
--- a/packages/summary-codecoverage/action.yml
+++ b/packages/summary-codecoverage/action.yml
@@ -1,161 +1,261 @@
-name: 'Summary - Publish test results'
-description: 'Summary - Publish test results'
+name: "Deploys a service to Cloudhub/GovCloud"
+description: "Deploys a service to Cloudhub/GovCloud"
+inputs:
+  pushover_token:
+    description: "Pushover application token"
+    required: true
+  pushover_user:
+    description: "Pushover user key"
+    required: true
+  application_name:
+    required: true
+    default: "cca-demo-sapi"
+    description: The name of the application the deployment issue was created for
+  environment:
+    required: true
+    default: "dev"
+    description: The enmviropnment the deployment issue is calling for
+  version:
+    required: true
+    default: "1.0.10"
+    description: The version of the application to be deployed to the environment
+outputs:
+  outcome:
+    description: "The result of the deployment: sucess, failure"
+    value: ${{ steps.deployment.outputs.outcome }}
 
 runs:
   using: "composite"
   steps:
-
-    - name: Initialize variables
-      shell: bash
-      run: |
-        echo " "
-        echo "*****************************************************"
-        echo "Code Coverage - Initializing variables"
-        echo "*****************************************************"
-        echo " "
-        # Set the initial values for the badge status and color
-        echo "BADGE_STATUS=Error parsing" >> $GITHUB_ENV
-        echo "BADGE_COLOR=800000" >> $GITHUB_ENV
-
-    - name: Publish - Application Coverage Report
-      if: ${{ hashFiles('target/site/munit/coverage/*') != '' }}
-      uses: actions/upload-artifact@master
+    - name: Install NodeJs
+      uses: actions/setup-node@v3
       with:
-        name: munit-application-coverage-report
-        path: target/site/munit/coverage/*
+        node-version: 20
 
-    - name: Summary - Add code coverage
-      id: summary-codecoverage
-      if: ${{ hashFiles('target/site/munit/coverage/summary.html') != '' }}
+    - name: Install Anypoint CLI
       shell: bash
       run: |
         echo " "
-        echo "*****************************************************"
-        echo "Code coverage - Get the summary report if exists"
-        echo "*****************************************************"
+        echo "***************************************"
+        echo "Install Anypoint CLI"
+        echo "***************************************"
+        echo " "
+        echo "Install anypoint-cli-v4..."
+        npm install -g anypoint-cli-v4
+        echo "anypoint-cli-v4 --version: "
+        anypoint-cli-v4 --version
+        echo " "
+        echo "Installing cloudhub-plugin"
+        anypoint-cli-v4 plugins:install anypoint-cli-cloudhub-plugin
         echo " "
 
-        summary_report=target/site/munit/coverage/summary.html
+    - id: deployment
+      name: Deploy the service to CloudHub1
+      shell: bash
+      run: |
+        echo " "
+        echo "************************************************************"
+        echo "Deploy the service to CloudHub1, mulesoft environment: $configuration_deployment_mulesoft_environment"
+        echo "************************************************************"
+        echo " "
+        # Environment variables:
+        # - configuration_deployment_name
+        # - configuration_deployment_organization
+        # - configuration_deployment_host
+        # - configuration_deployment_mulesoft_environment
+        # - configuration_cloudhub
+        # - cicd_connectedapp_clientid
+        # - cicd_connectedapp_secret
 
-        # Verify if summary report exists
-        if test -f "$summary_report"; then
+        # Get the jar file
+        jar=$(ls *.jar)
+        echo "Jar file: $jar"
 
-          temporal=""
-          line=0
-          trigger=0
-          while IFS= read -r p; do
+        start=$(date +%s)
+        echo " "
+        echo "Deployment process start. "
+        echo "   anypoint-cli-v4: $(anypoint-cli-v4 --version)"
 
-            if [[ "$p" == *"<div class=\"col-md-8 col-md-offset-2\">"* ]]; then
-              echo "Summary starts at line: $line"
-              ((line=line+1))
-              trigger=1
-              continue
-            fi
+        QUERY_STATUS="anypoint-cli-v4 runtime-mgr cloudhub-application describe \
+                    --client_id $cicd_connectedapp_clientid \
+                    --client_secret $cicd_connectedapp_secret \
+                    --environment $configuration_deployment_mulesoft_environment \
+                    --organization $configuration_deployment_organization \
+                    --host $configuration_deployment_host \
+                    --output json $configuration_deployment_name"
 
-            if [[ $trigger == 1 ]]; then
-              # echo "${p:0:6}"
-              echo "$p"
-              if [[ "${p:0:6}" == "</div>" ]]; then
-                echo "Exit condition at line: $line"
-                break
-              else
-                temporal+=$p
+        # Get the current status of the service
+        echo " "
+        echo "Getting the current status for the service"
+        echo "  Query command: $QUERY_STATUS"
+
+        # Get the current status of the service
+        DEPLOYMENT_INFO=$($QUERY_STATUS || true)
+        echo " "
+        echo "Current status: $DEPLOYMENT_INFO"
+
+        echo " "
+        echo "Querying variables from deployment result"
+        STATUS=$(echo $DEPLOYMENT_INFO | jq -r ".status")
+        UPDATE_STATUS=$(echo $DEPLOYMENT_INFO | jq -r ".deploymentUpdateStatus")
+
+        echo " "
+        echo "Result"
+        echo "  Service: $configuration_deployment_name status: $STATUS, updateStatus: $UPDATE_STATUS"
+        echo " "
+
+        # Verify if the service is currently in an inconsistent state
+        if [ "$STATUS" = "UNDEPLOYED" ]; then
+          echo "The service is in an inconsistent state: UNDEPLOYED; please delete the service"
+          echo "outcome=failure" >> $GITHUB_OUTPUT
+          exit 1 # terminate and indicate error
+        fi
+
+        if [ "$STATUS" = "DEPLOYING" ]; then
+          echo "The service was already in DEPLOYING state, wait until deployment finish or delete it"
+          echo "outcome=failure" >> $GITHUB_OUTPUT
+          exit 1 # terminate and indicate error
+        fi
+
+        # Verify if deployment is for an new application of update an existing one
+        if [ "$STATUS" != "" ]; then
+          operation="modify"
+        else
+          operation="deploy"
+        fi
+
+        # Execute deployment of the service
+        echo ""
+        echo "Based on the current status of the service, the deployment operation will be: $operation"
+        end=$(date +%s)
+        echo "  Elapsed time: $(($end-$start)) seconds"
+        echo " "
+        echo "Preparing deployment command...."
+        CREATEUPDATE_APP="anypoint-cli-v4 runtime-mgr cloudhub-application $operation \
+        --client_id $cicd_connectedapp_clientid \
+        --client_secret $cicd_connectedapp_secret \
+        --organization $configuration_deployment_organization \
+        --host $configuration_deployment_host \
+        --environment $configuration_deployment_mulesoft_environment \
+        $configuration_cloudhub --output json $configuration_deployment_name $jar"
+        echo "  Deployment command: $CREATEUPDATE_APP"
+        echo " "
+        echo "Executing deployment...."
+
+        $CREATEUPDATE_APP
+        end=$(date +%s)
+        echo " "
+        echo "Deployment finished, verifying the deployment...."
+        echo "  Elapsed time: $(($end-$start)) seconds"
+        echo " "
+
+        # Process to verify if the service was deployed correctly
+        echo " "
+        echo "**********************************"
+        echo "Deployment query cycle"
+        echo "**********************************"
+        echo " "
+        echo "The process of querying deployment starts"
+        iteration=1
+        limit=70
+        while true
+        do
+          sleep 5
+
+          # Get the current status of the service
+          echo " "
+          echo "Getting deployment status"
+          DEPLOYMENT_INFO=$($QUERY_STATUS)
+          # echo "Quering status: $DEPLOYMENT_INFO"
+          STATUS=$(echo $DEPLOYMENT_INFO | jq -r ".status")
+          UPDATE_STATUS=$(echo $DEPLOYMENT_INFO | jq -r ".deploymentUpdateStatus")
+          echo "Service: $configuration_deployment_name, operation: $operation, status: $STATUS, updateStatus: $UPDATE_STATUS"
+
+          end=$(date +%s)
+          echo "  Elapsed time: $(($end-$start)) seconds, iteration: $iteration limit: $limit"
+
+          if [ "$operation" = "deploy" ]; then
+              # Create service
+
+              if [ "$STATUS" = "STARTED" ] || [ $iteration -eq $limit ]; then
+                break # Abandon the while loop.
               fi
-            fi
+          else
+              # Update service
+              if [ "$UPDATE_STATUS" = "null" ] || [ "$UPDATE_STATUS" = "DEPLOY_FAILED" ] || [ $iteration -eq $limit ]; then
+                break # Abandon the while loop.
+              fi
+          fi
 
-            ((line=line+1))
-          done < $summary_report
+          echo "  Waiting for next query status iteration"
+          iteration=$(( $iteration + 1 ))
+        done
 
-          # Remove html tag: <a>
-          temporal=$(sed -e 's/<\/a[^>]*>//g' <<<"$temporal")
-          temporal=$(sed -e 's/<a[^>]*>//g' <<<"$temporal")
-
-          # Add job summary
-          echo "<div>" >> $GITHUB_STEP_SUMMARY
-          echo "$temporal" >> $GITHUB_STEP_SUMMARY
-          echo "</div>" >> $GITHUB_STEP_SUMMARY
-
-          # The coverage process was executed
-          # echo "COVERAGE_PROCESS='True'" >> $GITHUB_ENV
-          echo "CODE_COVERAGE_EXECUTION=true" >> $GITHUB_OUTPUT
-        else
-          # There is no summary report
-          # echo "COVERAGE_PROCESS='False'" >> $GITHUB_ENV
-          echo "CODE_COVERAGE_EXECUTION=false" >> $GITHUB_OUTPUT
-        fi
-
-    # - name: Set the code coverage results as environment variable
-    #   if: steps.summary-codecoverage.outputs.CODE_COVERAGE_EXECUTION == 'true'
-    #   id: json_var
-    #   shell: bash
-    #   run: |
-    #     echo " "
-    #     echo "******************************************************"
-    #     echo "Code coverage - export the summary report as env var"
-    #     echo "******************************************************"
-    #     echo " "
-
-    #     content=`cat target/site/munit/coverage/munit-coverage.json`
-    #     # the following lines are only required for multi line json
-    #     # content="${content//'%'/'%25'}"
-    #     # content="${content//$'\n'/'%0A'}"
-    #     # content="${content//$'\r'/'%0D'}"
-    #     # end of optional handling for multi line json
-    #     # sed -i -e 's/%/%25/g' -e ':a' -e 'N' -e '$!ba' -e 's/\n/%0A/g' -e 's/\r/%0D/g' target/site/munit/coverage/munit-coverage.json
-    #     cat target/site/munit/coverage/munit-coverage.json
-    #     echo "packageJson=$content" >> $GITHUB_OUTPUT
-    #     echo " "
-    #     echo "*****************************************************"
-
-    - name: Set badge color and code coverage as integer
-      if: steps.summary-codecoverage.outputs.CODE_COVERAGE_EXECUTION == 'true'
-      shell: bash
-      run: |
+        # Verify if service was successfully deployed
         echo " "
-        echo "*****************************************************"
-        echo "Code coverage - Set badge color and status"
-        echo "*****************************************************"
+        echo "**********************************"
+        echo "Analyse the deployment process"
+        echo "**********************************"
         echo " "
+        echo "The deployment process finished, lets analyse the result based on the last deployment status"
+        if [ "$operation" = "deploy" ]; then
 
-        report_file="target/site/munit/coverage/munit-coverage.json"
-        coverage=$(jq -r '.coverage' $report_file)
-        minimum=$(jq -r '.requiredApplicationCoverage' $report_file)
+          # Create new service
+          if [ "$STATUS" != "STARTED" ]; then
+            echo "  Error: The service was not deployed in the expected time, review logs"
+            echo "    example: anypoint-cli-v4 runtime-mgr cloudhub-application download-logs {APP-NAME}"
+            echo "  The expected iterations were 44 but the proccess reached the limit: $limit"
+            echo "outcome=failure" >> $GITHUB_OUTPUT
+            exit 1 # terminate and indicate error
 
-        # coverage_float=${{ fromJSON(steps.json_var.outputs.packageJson).coverage }}
-        # coverage=${coverage_float%.*}
-        # minimum=${{ fromJSON(steps.json_var.outputs.packageJson).requiredApplicationCoverage }}
-        echo "Application coverage: $coverage"
-        echo "Minimum: $minimum"
-        echo "BADGE_STATUS=$coverage of $minimum %" >> $GITHUB_ENV
-
-        if [[ "$((coverage))" -ge "$((minimum))" ]]; then
-          echo "BADGE_COLOR=31c653" >> $GITHUB_ENV
-          echo "  Code coverage is equal or greater than minimum"
+          else
+            echo "  Deployment successful.."
+            echo "outcome=success" >> $GITHUB_OUTPUT
+          fi
         else
-          echo "BADGE_COLOR=800000" >> $GITHUB_ENV
-          echo "  Code coverage is less than minimum"
+          # Update service
+          if [ "$UPDATE_STATUS" = "DEPLOY_FAILED" ]; then
+            echo "  Error: There were errors while deploying the service"
+            echo "outcome=failure" >> $GITHUB_OUTPUT
+            echo "  Last deployment information: $DEPLOYMENT_INFO"
+            exit 1 # terminate and indicate error
+
+          elif [ "$UPDATE_STATUS" = "null" ] && [ "$STATUS" = "UNDEPLOYED" ]; then
+            echo "  Error: There were errors while deploying the service"
+            echo "outcome=failure" >> $GITHUB_OUTPUT
+            echo "  Last deployment information: $DEPLOYMENT_INFO"
+            exit 1 # terminate and indicate error
+
+          elif [ "$UPDATE_STATUS" = "null" ] && [ "$STATUS" = "DEPLOY_FAILED" ]; then
+            echo "  Error: There were errors while deploying the service"
+            echo "outcome=failure" >> $GITHUB_OUTPUT
+            echo "  Last deployment information: $DEPLOYMENT_INFO"
+            exit 1 # terminate and indicate error
+
+          elif [ $iteration -eq $limit ]; then
+            echo "  Error: The service was not deployed in the expected time, review logs"
+            echo "    example: anypoint-cli-v4 runtime-mgr cloudhub-application download-logs {APP-NAME}"
+            echo "  The expected iterations were 44 but the proccess reached the limit: $limit"
+            echo "outcome=failure" >> $GITHUB_OUTPUT
+            exit 1 # terminate and indicate error
+
+          else
+            echo "  Deployment successful.."
+            echo "outcome=success" >> $GITHUB_OUTPUT
+          fi
         fi
         echo " "
 
-    - name: Badge for skipped tests
-      if: ${{ hashFiles('target/site/munit/coverage/summary.html') == '' }}
-      shell: bash
-      run: |
-        echo " "
-        echo "*****************************************************"
-        echo "Code coverage - Badge color for skipped tests"
-        echo "*****************************************************"
-        echo " "
-        echo "BADGE_COLOR=31c653" >> $GITHUB_ENV
-        echo "BADGE_STATUS=Skipped" >> $GITHUB_ENV
-        echo " "
-
-    - name: Create badge for code coverage
-      uses: CoveredCA/common-devops/packages/badge@main
-      if: always()
+    - name: Run pushover notify
+      id: Pushover
+      uses: CoveredCA/common-devops/packages/pushover-notify@main
       with:
-        label: Code coverage
-        status: ${{ env.BADGE_STATUS }}
-        color: ${{ env.BADGE_COLOR }}
-        file: ${{ env.service_name }}-cc.svg
-        folder: ${{ env.service_name }}
+        user: "${{ inputs.pushover_user }}"
+        token: "${{ inputs.pushover_token }}"
+        title: "${{ inputs.application_name }}" # Set the message title or leave empty
+        message: "<b>JOB:</b> 🚀 Deployment<br><b>APP:</b> ${{ inputs.application_name }}<br><b>VERSION:</b> ${{ inputs.version }}<br><b>ENV:</b> ${{ inputs.environment }}<br><b>OUTCOME:</b> ${{ steps.deployment.outputs.outcome == 'success' && '✅' || '❌'}}"
+        html: 1 # Set to 1 to enable HTML parsing or leave empty
+        priority: ${{ steps.deployment.outputs.outcome == 'success' && '0' || '1' }} # Set the priority value or leave empty
+        sound: "${{ steps.deployment.outputs.outcome == 'success' && 'bugle' || 'falling'}}" # Specify the sound name or leave empty
+        url: "https://www.github.com/CoveredCA/${{ inputs.application_name }}/actions/runs/${{ github.run_id }}" # Add the URL or leave empty
+        url_title: "Go To GitHub Actions Log" # Add the URL title or leave empty
