👌 IMPROVE: Get Secrets from Azure

diff --git a/packages/get-file/action.yml b/packages/get-file/action.yml
--- a/packages/get-file/action.yml
+++ b/packages/get-file/action.yml
@@ -4,11 +4,11 @@ inputs:
   file: 
     required: true
     description: File to download
+  checkIfExists:
+    required: false
+    description: Verify if file exists
+    default: 'false'
 
-outputs:
-  configuration-data:
-    description: "The contents of the configuration file"
-    value: ${{ steps.configuration.outputs.configuration-data }}
 runs:
   using: "composite"
   steps:
@@ -17,13 +17,12 @@ runs:
       name: Get configuration for the service 
       shell: bash
       run: |
-
         echo " "
         echo "*********************************************"
         echo "Get configuration file"
         echo "*********************************************"
         echo " "
-        echo "github_admintasks_accesstoken: $github_admintasks_accesstoken"
+        echo "github_automationbot_token: $github_automationbot_token"
         echo "inputs.file: ${{ inputs.file }}"
         listFiles="${{ inputs.file }}"
         for readFile in $listFiles
@@ -32,18 +31,24 @@ runs:
           echo "  Getting the file: $readFile"
           urlconfigurationfile="https://raw.githubusercontent.com/${{ github.repository_owner }}/$CONFIGURATIONS_REPOSITORY/main/$readFile"
           echo "  URL of file: $urlconfigurationfile"
-          configurationdata=$(curl -sH "Authorization: token $github_admintasks_accesstoken" $urlconfigurationfile)
+          configurationdata=$(curl -sH "Authorization: token $github_automationbot_token" $urlconfigurationfile)
 
           # Verify if configuration file was found
           if [[ $configurationdata != *"Not Found"* ]]; then
             echo "  The file was found"
             echo "$configurationdata" > $readFile
           else
-            echo "  File not found, returning an empty file"
-            touch $readFile
+            if [[ ${{ inputs.checkIfExists }} == "true" ]]; then
+              echo "  File not found, aborting the pipeline"
+              exit 1
+            else
+              echo "  File not found, returning an empty file"
+              touch $readFile
+            fi
           fi
 
           echo "  Set the output of the action with the value of the file"
           # echo "$configurationdata"
-          echo "configuration-data=$(echo $configurationdata)" >> $GITHUB_OUTPUT
+          echo "configuration_data=$(echo $configurationdata)" >> $GITHUB_ENV
         done
+        echo " "
