👌 IMPROVE: Add Github App for configuration management

diff --git a/.github/workflows/mule-build.yml b/.github/workflows/mule-build.yml
--- a/.github/workflows/mule-build.yml
+++ b/.github/workflows/mule-build.yml
@@ -24,7 +24,7 @@ jobs:
 
       - name: Get token from Github App
         id: app-token
-        uses: CoveredCA/common-devops/packages/secrets-azure@main
+        uses: CoveredCA/common-devops/packages/app-token@main
         with:
           client-id: ${{ secrets.MULESOFT_GITHUBAPP_CLIENTID}}
           privatekey: ${{ secrets.MULESOFT_GITHUBAPP_PRIVATEKEY }}
@@ -38,3 +38,25 @@ jobs:
 
       - name: Get service configuration
         uses: CoveredCA/common-devops/packages/configuration-service@main
+
+      - name: Verify if the github tag exists
+        if: "!contains(env.service_version, 'snapshot')"
+        shell: bash
+        run: |
+          echo " "
+          echo "***********************************************"
+          echo "Verify if github tag exists "
+          echo "***********************************************"
+          echo " "
+
+          tag_exist=$(git tag $service_version)
+          if [ "$tag_exist" != "" ] ; then
+            echo "  Error, the tag already exists in Github; bump up the application version in the POM file"
+            exit 1
+          else
+            echo "  Create tag $service_version for the respository"
+          fi
+          echo " "
+
+      - name: Install Java environment for Mulesoft Applications
+        uses: CoveredCA/common-devops/packages/install-javav2@main
